actor_l2: 0
actor_lr: 1e-4
actor_clip: None
adv_method: mean
adv_method_n: 4
buffer_size: 1000000
beta: 1
batch_size: 1024
crr_function: binary
critic_l2: 0
critic_clip: None
dist_impl: pyd
eval_interval: 5000
eval_episodes: 10
gamma: 0.99
gradient_updates_per_step: 1
log_std_low: -10
log_std_high: 2 
max_episode_steps: 100000
num_steps_online: 50000
num_steps_offline: 500000
name: awac_run
tau: 0.005
transitions_per_online_step: 1
target_delay: 2
state_space_size: 















